/// PrivacyPool — fixed-denomination shielded pool on Starknet.
///
/// Architecture:
///   Each deposit creates a secp256k1 "note" keypair held only by the depositor.
///   The commitment (hash of note pubkey) is stored on-chain. Withdrawals prove
///   knowledge of the note private key via secp256k1 signature — no link to the
///   depositor's identity at withdrawal time.
///
/// Privacy model:
///   - Fixed denomination (1 STRK) creates anonymity set.
///   - Deposit address and withdrawal address are fully decoupled.
///   - Withdrawal is relayed gaslessly — recipient never needs STRK.
///   - Note: commitment preimage is revealed at withdrawal. Full ZK privacy
///     (Merkle membership proof via Garaga) is the V2 upgrade path.
///
/// Note format:
///   note = secp256k1 keypair (sk, pk) generated by depositor
///   commitment  = poseidon(['pool_note_v1', pk.x_low, pk.x_high, pk.parity])
///   nullifier   = poseidon(['pool_null_v1', pk.x_low, pk.x_high, pk.parity])
///   withdrawal  signs: bitcoin_message_hash(poseidon(nullifier, recipient))

// ── ERC20 minimal interface ────────────────────────────────────────────────────

#[starknet::interface]
pub trait IERC20Pool<TState> {
    fn transfer(ref self: TState, recipient: starknet::ContractAddress, amount: u256) -> bool;
    fn transfer_from(
        ref self: TState,
        sender: starknet::ContractAddress,
        recipient: starknet::ContractAddress,
        amount: u256,
    ) -> bool;
}

// ── IPrivacyPool interface ────────────────────────────────────────────────────

#[starknet::interface]
pub trait IPrivacyPool<TState> {
    /// Deposit exactly 1 STRK and register a note commitment.
    /// commitment = poseidon(['pool_note_v1', note_pk.x_low, note_pk.x_high, note_pk.parity])
    /// Caller must approve this contract for 1 STRK before calling.
    fn deposit(ref self: TState, commitment: felt252);

    /// Withdraw 1 STRK to recipient by proving ownership of the note private key.
    /// note_pubkey_{x,y}: the note's secp256k1 public key (uncompressed coords)
    /// recipient: address to receive the STRK
    /// sig: secp256k1 signature over bitcoin_message_hash(poseidon(nullifier, recipient))
    fn withdraw(
        ref self: TState,
        note_pubkey_x: u256,
        note_pubkey_y: u256,
        recipient: starknet::ContractAddress,
        sig: Array<felt252>,
    );

    fn deposit_count(self: @TState) -> u64;
    fn is_commitment_active(self: @TState, commitment: felt252) -> bool;
    fn is_nullifier_used(self: @TState, nullifier: felt252) -> bool;
}

// ── Contract ───────────────────────────────────────────────────────────────────

#[starknet::contract]
pub mod PrivacyPool {
    use starknet::{ContractAddress, get_caller_address, get_contract_address};
    use starknet::storage::{Map, StorageMapReadAccess, StorageMapWriteAccess};
    use starknet::storage::{StoragePointerReadAccess, StoragePointerWriteAccess};
    use starknet::secp256k1::Secp256k1Point;
    use starknet::secp256_trait::{Secp256Trait, is_valid_signature};
    use core::poseidon::poseidon_hash_span;
    use super::{IERC20PoolDispatcher, IERC20PoolDispatcherTrait};
    use crate::utils::{decode_signature, bitcoin_message_hash};

    /// STRK token on Starknet Sepolia.
    fn strk_token() -> ContractAddress {
        let addr: felt252 = 0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d;
        addr.try_into().unwrap()
    }

    /// Fixed denomination: 1 STRK = 10^18 wei.
    const DENOMINATION: u128 = 1_000_000_000_000_000_000_u128;

    // Domain separators — keep commitment and nullifier in separate hash domains.
    const NOTE_DOMAIN: felt252 = 'pool_note_v1';
    const NULL_DOMAIN: felt252 = 'pool_null_v1';

    // ── Storage ────────────────────────────────────────────────────────────────

    #[storage]
    struct Storage {
        /// Active commitments: commitment → true if deposited and unspent.
        commitments: Map<felt252, bool>,
        /// Spent nullifiers: nullifier → true once withdrawn.
        nullifiers: Map<felt252, bool>,
        /// Total deposit count (for anonymity-set display).
        count: u64,
    }

    // ── Events ─────────────────────────────────────────────────────────────────

    #[event]
    #[derive(Drop, starknet::Event)]
    pub enum Event {
        Deposited: Deposited,
        Withdrawn: Withdrawn,
    }

    /// Emitted at deposit. commitment is public; depositor identity is the caller.
    #[derive(Drop, starknet::Event)]
    pub struct Deposited {
        #[key]
        pub commitment: felt252,
        pub deposit_index: u64,
    }

    /// Emitted at withdrawal. nullifier is public; does NOT reveal which commitment was spent.
    #[derive(Drop, starknet::Event)]
    pub struct Withdrawn {
        #[key]
        pub nullifier: felt252,
        pub recipient: ContractAddress,
    }

    // ── Constructor ────────────────────────────────────────────────────────────

    #[constructor]
    fn constructor(ref self: ContractState) {}

    // ── IPrivacyPool ───────────────────────────────────────────────────────────

    #[abi(embed_v0)]
    impl PrivacyPoolImpl of super::IPrivacyPool<ContractState> {
        fn deposit(ref self: ContractState, commitment: felt252) {
            assert(!self.commitments.read(commitment), 'Commitment already used');

            // Pull exactly 1 STRK from caller
            let denomination = u256 { low: DENOMINATION, high: 0 };
            let ok = IERC20PoolDispatcher { contract_address: strk_token() }
                .transfer_from(get_caller_address(), get_contract_address(), denomination);
            assert(ok, 'STRK transfer failed');

            let index = self.count.read();
            self.commitments.write(commitment, true);
            self.count.write(index + 1);

            self.emit(Deposited { commitment, deposit_index: index });
        }

        fn withdraw(
            ref self: ContractState,
            note_pubkey_x: u256,
            note_pubkey_y: u256,
            recipient: ContractAddress,
            sig: Array<felt252>,
        ) {
            // Derive commitment and nullifier from note pubkey
            let x_low: felt252 = note_pubkey_x.low.into();
            let x_high: felt252 = note_pubkey_x.high.into();
            // parity: 0 if y is even, 1 if odd
            let parity: felt252 = (note_pubkey_y.low & 1_u128).into();

            let commitment = poseidon_hash_span(
                array![NOTE_DOMAIN, x_low, x_high, parity].span(),
            );
            let nullifier = poseidon_hash_span(
                array![NULL_DOMAIN, x_low, x_high, parity].span(),
            );

            // Verify commitment exists and nullifier is fresh
            assert(self.commitments.read(commitment), 'No such commitment');
            assert(!self.nullifiers.read(nullifier), 'Note already spent');

            // Verify note ownership: sig over bitcoin_message_hash(poseidon(nullifier, recipient))
            let recipient_felt: felt252 = recipient.into();
            let msg_felt = poseidon_hash_span(array![nullifier, recipient_felt].span());
            let msg_hash = bitcoin_message_hash(msg_felt);

            let (r, s) = decode_signature(sig.span()).expect('Invalid sig format');
            let pubkey = match Secp256Trait::<Secp256k1Point>::secp256_ec_new_syscall(
                note_pubkey_x, note_pubkey_y,
            ) {
                Result::Ok(Option::Some(p)) => p,
                _ => panic!("Invalid note pubkey"),
            };
            assert(is_valid_signature::<Secp256k1Point>(msg_hash, r, s, pubkey), 'Invalid note sig');

            // Mark nullifier as spent, keep commitment (for Merkle history)
            self.nullifiers.write(nullifier, true);
            self.commitments.write(commitment, false); // deactivate

            // Transfer 1 STRK to recipient
            let denomination = u256 { low: DENOMINATION, high: 0 };
            let ok = IERC20PoolDispatcher { contract_address: strk_token() }
                .transfer(recipient, denomination);
            assert(ok, 'STRK transfer failed');

            self.emit(Withdrawn { nullifier, recipient });
        }

        fn deposit_count(self: @ContractState) -> u64 {
            self.count.read()
        }

        fn is_commitment_active(self: @ContractState, commitment: felt252) -> bool {
            self.commitments.read(commitment)
        }

        fn is_nullifier_used(self: @ContractState, nullifier: felt252) -> bool {
            self.nullifiers.read(nullifier)
        }
    }
}
